name: Cheat finder

on:
  workflow_dispatch:
    inputs:
      start:
        type: string
        required: true
      end:
        type: string
        required: true
      alphabet: 
        type: string
        default: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: oven-sh/setup-bun@main
    - name: Prepare data
      run: |
        bun gtasacchcf.js -s ${{ inputs.start }} -e ${{ inputs.end }} -a ${{ inputs.alphabet }}
        bun tsv.js
    - name: Git changes
      run: |
        git -c user.name="github-actions[bot]" -c user.email="github-actions[bot]@users.noreply.github.com" commit -a -m "[action] New data"
        gh pr create --head --fill-first
      env:
        GH_TOKEN: ${{ github.token }}
