name: Cheat finder

on:
  workflow_dispatch:
    inputs:
      start:
        type: string
        required: true
      end:
        type: string
        required: true
      alphabet: 
        type: string
        default: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: oven-sh/setup-bun@main
    - name: Prepare data
      run: |
        bun gtasacchcf.js -s ${{ inputs.start }} -e ${{ inputs.end }} -a ${{ inputs.alphabet }}
        bun tsv.js
    - name: Git actions
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git branch newdata
        git checkout newdata
        git add data
        git commit --message="[action] new data"
        git push --set-upstream origin newdata
        gh pr create --title="[action] new data" --body="start: ${{ inputs.start }}\nend: ${{ inputs.end }}\nalphabet: ${{ inputs.alphabet }}" --base="main" --head="newdata"
      env:
        GH_TOKEN: ${{ github.token }}
