name: Cheat finder

on:
  workflow_dispatch:
    inputs:
      start:
        type: string
        required: true
      end:
        type: string
        required: true
      alphabet: 
        type: string
        default: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: oven-sh/setup-bun@main
    - run: |
        bun gtasacchcf.js -s ${{ inputs.start }} -e ${{ inputs.end }} -a ${{ inputs.alphabet }}
        bun tsv.js
    - run: |
        # git config user.name "github-actions[bot]"
        # git config user.email "github-actions[bot]@users.noreply.github.com"
        # git add data/
        git commit -a -m "[action] Cheat finder" --author="github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
        gh pr create --head --fill
